# Generated by Django 5.1 on 2024-11-08 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('section_title', models.CharField(max_length=200)),
                ('section_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Layanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_layanan', models.CharField(max_length=200)),
                ('gambar', models.ImageField(blank=True, null=True, upload_to='services/images/')),
                ('deskripsi_layanan', models.TextField()),
                ('service_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layanan', to='services.servicepage')),
            ],
        ),
    ]
