# Generated by Django 5.1 on 2024-11-17 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_article_likes_article_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='comments_count',
        ),
    ]
