# Generated by Django 5.1 on 2024-11-16 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_homeimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimoni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(help_text='Nama pengirim testimoni', max_length=100)),
                ('isi_testimoni', models.TextField(help_text='Isi testimoni')),
            ],
        ),
    ]
