# Generated by Django 5.1 on 2024-11-15 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp_number', models.CharField(help_text='Masukkan nomor WhatsApp dalam format internasional, misalnya: +628123456789', max_length=15)),
            ],
        ),
    ]
